#!/usr/bin/env python3
"""Retain generated Bazel dependency evidence after a successful native build."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess


PLATFORMS = {
    "AMD64": ("x86_64", "@sonic_build_infra//platforms:x86_64_trixie"),
    "ARM64": ("aarch64", "@sonic_build_infra//platforms:aarch64_trixie"),
}


def collect_resolution(output, mode, architecture, bazel_command=None):
    machine, target = PLATFORMS[architecture]
    if platform.machine() != machine or os.environ.get("RUNNER_ARCH", architecture).upper() not in {
            architecture, "X64" if architecture == "AMD64" else "ARM64"}:
        raise RuntimeError("Resolution evidence must come from the declared native architecture")
    # Container checkout ownership can differ from the user running this step.
    # Trust only this checkout, for these read-only Git commands.
    git = ["git", "-c", f"safe.directory={Path.cwd().resolve()}"]
    if subprocess.check_output(git + ["ls-files", "MODULE.bazel.lock"], text=True).strip():
        raise RuntimeError("MODULE.bazel.lock must remain generated and untracked")
    subprocess.run(git + ["check-ignore", "-q", "MODULE.bazel.lock"], check=True)
    # Preserve the build's lock before asking Bazel for the resolved graph.
    build_lock = Path("MODULE.bazel.lock").read_bytes()
    json.loads(build_lock)
    command = (bazel_command or ["bazel"]) + [
        "mod", "graph", "--output=json", "--lockfile_mode=update",
    ]
    graph = subprocess.check_output(command)
    parsed = json.loads(graph)
    if not isinstance(parsed, dict) or not parsed.get("name"):
        raise RuntimeError("Bazel did not return a module graph")
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    files = {
        "MODULE.bazel.lock": build_lock,
        "module-graph.json": graph,
        "module-graph.lock": Path("MODULE.bazel.lock").read_bytes(),
        "MODULE.bazel": Path("MODULE.bazel").read_bytes(),
        "bazelrc.txt": Path(".bazelrc").read_bytes(),
    }
    receipt = {
        "revision": subprocess.check_output(git + ["rev-parse", "HEAD"], text=True).strip(),
        "tree": subprocess.check_output(git + ["rev-parse", "HEAD^{tree}"], text=True).strip(),
        "mode": mode,
        "runner_architecture": os.environ.get("RUNNER_ARCH", architecture),
        "userspace_machine": platform.machine(),
        "target_platform": target,
        "graph_command": command,
        "lock_origin": "Generated by this native build; graph resolution retained separately",
        "files": {},
    }
    for name, data in files.items():
        path = output / name
        path.write_bytes(data)
        expected = hashlib.sha256(data).hexdigest()
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise RuntimeError("Evidence checksum mismatch: " + name)
        receipt["files"][name] = {"sha256": expected, "bytes": len(data)}
    (output / "resolution.json").write_text(json.dumps(receipt, indent=2) + "\n")
    return receipt


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True)
    parser.add_argument("--mode", choices=["yang", "no-yang"], required=True)
    parser.add_argument("--architecture", choices=sorted(PLATFORMS), required=True)
    args = parser.parse_args()
    collect_resolution(args.output, args.mode, args.architecture)


if __name__ == "__main__":
    main()
