load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

exports_files([
    "src/sonic-yang-models/README.rst",
    "src/sonic-yang-models/setup.py",
])

filegroup(
    name = "yang_model_sources",
    srcs = glob([
        "src/sonic-yang-models/yang-models/*.yang",
        "src/sonic-yang-models/yang-templates/*.yang.j2",
    ]),
)

py_library(
    name = "sonic_yang_mgmt",
    srcs = [
        "src/sonic-yang-mgmt/sonic_yang.py",
        "src/sonic-yang-mgmt/sonic_yang_ext.py",
        "src/sonic-yang-mgmt/sonic_yang_path.py",
    ],
    imports = ["src/sonic-yang-mgmt"],
    deps = [
        "@libyang_python//:libyang",
        "@swss_yang_pip//jsonpointer",
    ],
)
