#!/usr/bin/env python3
"""Prepare the shared third-party Rust graph before Bazel resolution."""

import hashlib
from pathlib import Path
import subprocess
import sys
import tempfile
import urllib.request


# This bootstrap pin is separate from the Bazel module version: preparation runs
# before Bazel can resolve the module graph. Keep the source and hash together.
PREPARATION_REVISION = "c13b2a8a7b9250c3e5c0da0d5d9c35d40f084bcb"
PREPARATION_SHA256 = "5847dcbc6a4098a8671c6802a490160097cf22f2bc306da329c7ae1d73334777"
PREPARATION_URL = (
    "https://raw.githubusercontent.com/securely1g/sonic-build-infra/"
    f"{PREPARATION_REVISION}/tools/rust/prepare.py"
)

RC_MARKER = "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"


def main():
    workspace = Path(__file__).resolve().parents[2]
    staging = workspace / "artifacts" / "rust-deps"
    overrides = staging / "overrides.bazelrc"
    # A failed download must not leave a previous dependency selection active.
    if overrides.is_symlink() or (overrides.exists() and not overrides.read_text().startswith(RC_MARKER)):
        raise SystemExit("Refusing to replace a non-generated Rust overrides file")
    overrides.unlink(missing_ok=True)
    with urllib.request.urlopen(PREPARATION_URL, timeout=60) as response:
        source = response.read()
    if hashlib.sha256(source).hexdigest() != PREPARATION_SHA256:
        raise SystemExit("Shared Rust preparation checksum mismatch")
    with tempfile.TemporaryDirectory(prefix="sonic-rust-preparation-") as temporary:
        helper = Path(temporary) / "prepare.py"
        helper.write_bytes(source)
        return subprocess.call([
            sys.executable,
            str(helper),
            "--workspace", str(workspace),
            "--shared-dependency=sonic-rust-deps=sonic_rust_deps",
            "--staging-dir", str(staging),
            "--overrides-rc", str(overrides),
            *sys.argv[1:],
        ])


if __name__ == "__main__":
    sys.exit(main())
