"""Declared SWIG interface adapter with explicit preprocessor directives."""

def _swig_interface_impl(ctx):
    lines = ["// Generated by the Bazel SWIG interface adapter."]
    lines.extend(["#undef " + name for name in ctx.attr.undefines])
    lines.extend(["#define " + name for name in ctx.attr.defines])
    lines.append('%include "{}"'.format(ctx.file.interface.basename))
    ctx.actions.write(ctx.outputs.out, "\n".join(lines) + "\n")
    return [DefaultInfo(files = depset([ctx.outputs.out]))]

swig_interface = rule(
    implementation = _swig_interface_impl,
    attrs = {
        "defines": attr.string_list(),
        "interface": attr.label(
            allow_single_file = [".i"],
            mandatory = True,
        ),
        "out": attr.output(mandatory = True),
        "undefines": attr.string_list(),
    },
    doc = "Writes a SWIG interface with explicit preprocessor directives. The caller must also pass the source interface as an input to swig_gen.",
)
